version: '3'

tasks:
  default:
    aliases:
      - list
    desc: |
      List all tasks in the Taskfile
    cmds:
      - task --list-all

  run:
    desc: |
      Run the main reflex script
    cmds:
      - cd src/presentation && uv run reflex run

  setup:
    desc: Set up the development environment
    cmds:
      - npm install
      - lefthook install

  cli-extract:
    aliases:
      - e
    desc: |
      Extract the TeX source code from the PDF at cli/result
    cmds:
      - cd cli && uv run extract.py

  cli-compile:
    aliases:
      - c
    desc: |
      Compile the TeX source code at cli/tex
    cmds:
      - cd cli && uv run compile.py
